# Description: Install Consul service discovery agent on every CCC node
#
# Context: CCC uses Consul for internal service mesh so no IP addresses or
#   personal domain names ever appear in source code. All required services
#   register themselves here and are reachable as <name>.service.consul.
#   Hub nodes (IS_HUB=true) run the Consul server; other nodes run agents.
#   The Consul binary is installed under ~/.ccc/consul/ (CCC-owned, not system).
#
# Removing CCC also removes Consul because all state lives under ~/.ccc/.
# Condition: all platforms (linux + macos)

CONSUL_VERSION="1.19.2"
CONSUL_DIR="$HOME/.ccc/consul"
CONSUL_BIN="$CONSUL_DIR/bin/consul"
CONSUL_DATA="$CONSUL_DIR/data"
CONSUL_SERVICES="$CONSUL_DIR/services"
CONSUL_CFG="$CONSUL_DIR/consul.hcl"

# ── Detect hub role ────────────────────────────────────────────────────────
IS_HUB="${IS_HUB:-false}"
if on_platform linux; then
    if [ -f "/usr/local/bin/ccc-server" ] || systemctl is-active --quiet ccc-server 2>/dev/null; then
        IS_HUB=true
    fi
fi
if [ "${HUB_NODE:-false}" = "true" ]; then IS_HUB=true; fi

# ── Create CCC-owned directories ───────────────────────────────────────────
mkdir -p "$CONSUL_DIR/bin" "$CONSUL_DATA" "$CONSUL_SERVICES"

# ── Download consul binary if not already installed ────────────────────────
if [ ! -x "$CONSUL_BIN" ]; then
    m_info "Downloading Consul $CONSUL_VERSION..."

    ARCH="$(uname -m)"
    case "$ARCH" in
        x86_64)        GOARCH="amd64" ;;
        aarch64|arm64) GOARCH="arm64" ;;
        *)
            m_warn "Unknown arch $ARCH — skipping consul install"
            return 0
            ;;
    esac

    if on_platform linux; then GOOS="linux"; fi
    if on_platform macos; then GOOS="darwin"; fi

    CONSUL_ZIP="consul_${CONSUL_VERSION}_${GOOS}_${GOARCH}.zip"
    CONSUL_URL="https://releases.hashicorp.com/consul/${CONSUL_VERSION}/${CONSUL_ZIP}"
    TMP_ZIP=$(mktemp /tmp/consul-XXXXX.zip)
    TMP_DIR=$(mktemp -d /tmp/consul-extract-XXXXX)

    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$CONSUL_URL" -o "$TMP_ZIP" || { m_warn "curl download failed"; rm -rf "$TMP_ZIP" "$TMP_DIR"; return 0; }
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$CONSUL_URL" -O "$TMP_ZIP" || { m_warn "wget download failed"; rm -rf "$TMP_ZIP" "$TMP_DIR"; return 0; }
    else
        m_warn "Neither curl nor wget found — cannot download Consul"
        return 0
    fi

    if ! command -v unzip >/dev/null 2>&1; then
        m_warn "unzip not found — install it and re-run this migration"
        rm -rf "$TMP_ZIP" "$TMP_DIR"
        return 0
    fi

    unzip -q "$TMP_ZIP" consul -d "$TMP_DIR"
    mv "$TMP_DIR/consul" "$CONSUL_BIN"
    chmod +x "$CONSUL_BIN"
    rm -rf "$TMP_ZIP" "$TMP_DIR"
    m_success "Consul $CONSUL_VERSION installed to $CONSUL_BIN"
else
    INSTALLED_VER=$("$CONSUL_BIN" version 2>/dev/null | head -1 | awk '{print $2}' | tr -d 'v' || echo "unknown")
    m_info "Consul already present: v${INSTALLED_VER} (target: $CONSUL_VERSION)"
fi

# ── Resolve Tailscale IP ───────────────────────────────────────────────────
TAILSCALE_IP=""
if command -v tailscale >/dev/null 2>&1; then
    TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | head -1 || true)"
fi
if [ -z "$TAILSCALE_IP" ] && on_platform linux; then
    TAILSCALE_IP="$(ip -4 addr show tailscale0 2>/dev/null | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1 || true)"
fi
if [ -z "$TAILSCALE_IP" ]; then
    m_warn "Could not determine Tailscale IP — Consul will bind to 0.0.0.0 (suboptimal)"
    TAILSCALE_IP="0.0.0.0"
fi
m_info "Consul bind address: $TAILSCALE_IP"

# ── Build config parameters based on server vs agent role ─────────────────
if [ "$IS_HUB" = "true" ]; then
    IS_SERVER="true"
    BOOTSTRAP_LINE="bootstrap_expect = 1"
    RETRY_JOIN_LINE="# server mode — no retry_join needed"
    UI_ENABLED="true"
    m_info "Role: Consul SERVER (hub)"
else
    IS_SERVER="false"
    BOOTSTRAP_LINE=""
    UI_ENABLED="false"
    CONSUL_SERVER_ADDR="${CONSUL_SERVER_ADDR:-}"
    if [ -z "$CONSUL_SERVER_ADDR" ]; then
        m_warn "CONSUL_SERVER_ADDR not set in ~/.ccc/.env"
        m_warn "Add 'CONSUL_SERVER_ADDR=<rocky-tailscale-ip>' and re-run: bash deploy/run-migrations.sh --force=0009"
        return 0
    fi
    RETRY_JOIN_LINE="retry_join = [\"$CONSUL_SERVER_ADDR\"]"
    m_info "Role: Consul AGENT (server: $CONSUL_SERVER_ADDR)"
fi

# ── Render consul.hcl ─────────────────────────────────────────────────────
NODE="${AGENT_NAME:-$(hostname -s)}"
cat > "$CONSUL_CFG" << EOF
# Generated by CCC migration 0009 — do not edit by hand
# Re-run: bash deploy/run-migrations.sh --force=0009
datacenter = "ccc"
node_name  = "$NODE"
server     = $IS_SERVER
$BOOTSTRAP_LINE

bind_addr   = "$TAILSCALE_IP"
client_addr = "127.0.0.1"

data_dir     = "$CONSUL_DATA"
services_dir = "$CONSUL_SERVICES"

$RETRY_JOIN_LINE

ports {
  dns  = 8600
  http = 8500
  grpc = 8502
}

dns_config {
  allow_stale = true
}

ui_config {
  enabled = $UI_ENABLED
}

enable_local_script_checks = true
disable_remote_exec         = true
log_level                   = "INFO"

telemetry {
  disable_hostname          = true
  prometheus_retention_time = "24h"
}
EOF
m_success "consul.hcl rendered: $CONSUL_CFG"

# ── Copy node service definitions ──────────────────────────────────────────
SVCDEF="$WORKSPACE/deploy/consul/service-defs/${NODE}.hcl"
if [ -f "$SVCDEF" ]; then
    cp "$SVCDEF" "$CONSUL_SERVICES/${NODE}.hcl"
    m_success "Service definitions installed: ${NODE}.hcl"
else
    m_info "No service definitions for node '${NODE}' — agent registers no services"
fi

# ── Install and start Consul service ──────────────────────────────────────
if on_platform linux; then
    SVC_SRC="$WORKSPACE/deploy/systemd/consul.service"
    if [ ! -f "$SVC_SRC" ]; then
        m_warn "consul.service template not found: $SVC_SRC"
    else
        sed -e "s|AGENT_USER|$(whoami)|g" \
            -e "s|AGENT_HOME|$HOME|g" \
            "$SVC_SRC" | sudo tee /etc/systemd/system/consul.service > /dev/null
        sudo systemctl daemon-reload
        sudo systemctl enable consul.service 2>/dev/null || true
        sudo systemctl restart consul.service 2>/dev/null \
            && m_success "consul.service started" \
            || m_warn "consul.service failed to start — check: journalctl -u consul"
    fi
fi

if on_platform macos; then
    PLIST_SRC="$WORKSPACE/deploy/launchd/com.ccc.consul.plist"
    PLIST_DST="$HOME/Library/LaunchAgents/com.ccc.consul.plist"
    mkdir -p "$HOME/.ccc/logs"
    if [ ! -f "$PLIST_SRC" ]; then
        m_warn "com.ccc.consul.plist not found: $PLIST_SRC"
    else
        launchctl unload "$PLIST_DST" 2>/dev/null || true
        sed "s|AGENT_HOME|$HOME|g" "$PLIST_SRC" > "$PLIST_DST"
        launchctl load "$PLIST_DST" \
            && m_success "com.ccc.consul loaded" \
            || m_warn "launchctl load failed — check: tail -f $HOME/.ccc/logs/consul.log"
    fi
fi

m_success "Consul install complete"
m_info "Services reachable as: <name>.service.consul (after DNS migration 0010)"
m_info "Consul UI: http://127.0.0.1:8500 (hub only)"
