#!/usr/bin/env node
/**
 * rcc-hub setup wizard
 * Prompts for required config values and writes a .env file.
 */

import { createInterface } from 'readline';
import { writeFile, readFile, access } from 'fs/promises';
import { randomUUID } from 'crypto';
import { homedir } from 'os';
import { join } from 'path';

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def) => new Promise(resolve =>
  rl.question(def ? `${q} [${def}]: ` : `${q}: `, ans => resolve(ans.trim() || def || ''))
);

async function main() {
  console.log('\n🐿️  CCC Hub Setup Wizard\n');

  const envPath = '.env';
  try {
    await access(envPath);
    const overwrite = await ask('.env already exists. Overwrite? (y/N)', 'N');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Aborted. Existing .env kept.');
      process.exit(0);
    }
  } catch {}

  const port = await ask('Port to listen on', '8789');
  const publicUrl = await ask('Public URL (used in onboard scripts)', `http://localhost:${port}`);

  const adminToken = await ask('Admin token (leave blank to generate)', '');
  const agentToken = await ask('Agent token (leave blank to generate)', '');

  const tokenhubUrl = await ask('Tokenhub URL (optional — leave blank to skip)', '');
  const tokenhubKey = tokenhubUrl ? await ask('Tokenhub API key', '') : '';

  const slackBot = await ask('Slack bot token (optional — leave blank to skip)', '');
  const slackSign = slackBot ? await ask('Slack signing secret', '') : '';

  const milvusUrl = await ask('Milvus URL (optional — enables semantic dedup)', '');

  const squirrelBusUrl = await ask('ClawBus URL (optional)', '');
  const squirrelBusToken = squirrelBusUrl ? await ask('ClawBus token', '') : '';

  const finalAdmin = adminToken || `rcc-admin-${randomUUID().replace(/-/g, '').slice(0, 24)}`;
  const finalAgent = agentToken || `rcc-agent-${randomUUID().replace(/-/g, '').slice(0, 24)}`;

  const lines = [
    `# CCC Hub — generated by setup wizard`,
    `RCC_PORT=${port}`,
    `RCC_PUBLIC_URL=${publicUrl}`,
    `RCC_ADMIN_TOKEN=${finalAdmin}`,
    `RCC_AUTH_TOKENS=${finalAgent}`,
    ``,
  ];

  if (tokenhubUrl) {
    lines.push(`TOKENHUB_URL=${tokenhubUrl}`);
    if (tokenhubKey) lines.push(`TOKENHUB_API_KEY=${tokenhubKey}`);
    lines.push('');
  }

  if (slackBot) {
    lines.push(`SLACK_BOT_TOKEN=${slackBot}`);
    if (slackSign) lines.push(`SLACK_SIGNING_SECRET=${slackSign}`);
    lines.push('');
  }

  if (milvusUrl) {
    lines.push(`MILVUS_URL=${milvusUrl}`);
    lines.push(`MILVUS_ADDRESS=${milvusUrl.replace(/^https?:\/\//, '')}`);
    lines.push('');
  }

  if (squirrelBusUrl) {
    lines.push(`SQUIRRELBUS_URL=${squirrelBusUrl}`);
    if (squirrelBusToken) lines.push(`SQUIRRELBUS_TOKEN=${squirrelBusToken}`);
    lines.push('');
  }

  await writeFile(envPath, lines.join('\n'));

  console.log(`\n✅ .env written.\n`);
  console.log(`Admin token: ${finalAdmin}`);
  console.log(`Agent token: ${finalAgent}`);
  console.log(`\nStart with: npm start\n`);

  rl.close();
}

main().catch(e => { console.error(e); process.exit(1); });
